### ISSUE TITLE
3729 屏幕共享

### ISSUE THREAD

**Issue by 63isOK** [epubcn/cef_enhancement#1]
你好, cef支持屏幕共享,应用win_3729下的补丁后可以正常共享应用.其中有个特殊的情况:

共享多文档(测试例子可以参考打开ppt,然后F5播放,此时会有两个窗口,一个是原文档窗口,一个是全屏窗口.两窗口独立),
用现在的chrome 85测试如下:应用共享选择原文档,ppt播放之后,如果焦点在ppt全屏窗口时,**共享出来的是全屏窗口**,
打完win_3729补丁后,共享不会显示全屏窗口.

我猜测应该是chromium后面新增的功能,大佬能更新一下吗?或者给个思路指导一下.

**Comment by 63isOK** [comment]
@epubcn 用chrome85测试[屏幕共享](https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/)的结果并不理想,但在原文档最大化时,还是能解决很多问题的,下面是chrome85测试的结果:

chrome上屏幕共享+多文档全屏测试结果:
1. 共享区域:原始文档有多大就截多大的区域,拉伸之后再在网页上展示
2. 共享对象:如果焦点在全屏文档上,共享的是"全屏文档+原始文档",共享区域是原始文档大小;如果焦点在原始文档上,共享的是原始文档

**Comment by epubcn** [comment]
你的意思是Chromium 85是正常的，3729不正常是吗？

**Comment by epubcn** [comment]
> @epubcn 用chrome85测试[屏幕共享](https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/)的结果并不理想,但在原文档最大化时,还是能解决很多问题的,下面是chrome85测试的结果:
> 
> chrome上屏幕共享+多文档全屏测试结果:
> 
> 1. 共享区域:原始文档有多大就截多大的区域,拉伸之后再在网页上展示
> 2. 共享对象:如果焦点在全屏文档上,共享的是"全屏文档+原始文档",共享区域是原始文档大小;如果焦点在原始文档上,共享的是原始文档

你的意思是Chromium 85是正常的，3729不正常是吗？

**Comment by epubcn** [comment]
我上传了windows 4183（Chromium 85）的代码补丁。可以支持 getDisplayMedia 弹出选择框（选全屏幕或者某个应用窗口）。如果你描述的问题在 85上没问题，试试这个吧。 macOS的和Windows的代码补丁有少量不同，有空我整理一下。

**Comment by 63isOK** [comment]
大神您好.请先让我膜拜一下您开源的贡献.

3729没有不正常. 用Chromium 85测试发现针对多文档的全屏有部分支持,

1. 打开一个ppt
2. getDisplayMedia 选择ppt窗口并共享
3. ppt播放,(此时会出现一个新的全屏窗口)

结果就是共享出去的是全屏窗口.这个做法非常赞.

3729选择ppt窗口并共享,即使ppt播放,依然共享的是ppt窗口,不是那个全屏窗口.

所以不知道是不是3729之后,chromium新增的功能.

**Comment by 63isOK** [comment]
windows 4183 已下载,用cmake生成工程后,打开编译,生成的client.exe无法运行,报的错误是平台不兼容,win7/win10均是这样.

大神,是不是我对cmake打开的姿势不正确?

**Comment by 63isOK** [comment]
windows 4183我用的是您上传到csdn的版本编译的.
cef的编译我会用您上传的补丁做下测试.

**Comment by epubcn** [comment]
> windows 4183 已下载,用cmake生成工程后,打开编译,生成的client.exe无法运行,报的错误是平台不兼容,win7/win10均是这样.
> 
> 大神,是不是我对cmake打开的姿势不正确?

咦？这就很奇怪了。4183我已经正式在用了呢。我是做了个bat放到cef工程目录下执行，会生成单独的build目录。build目录下有sln。bat内容如下：

```
@echo 
rd /s /q build
md build
cd /d %~dp0\build
cmake -G "Visual Studio 15" .. -A Win32 -T v141
cd ..
pause
```

我的VS版本是2017 15.9.27。你不会是build了x64吧？CSDN上是win32版本的。

**Comment by 63isOK** [comment]
大神,我的系统是win7 x64, vs是2017 15.9.26, build的是32位,用的程序是CSDN上的win32版本.

之前只测试过debug版本,能编译成功,运行会报版本错误(win7/win10均出现).
用release版本则没问题.效果和Chromium 85的效果是一致的.

多谢大神对开源的贡献和对我的指导.非常感谢.
